//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amenity()
        {
            this.RoomAmenity = new HashSet<RoomAmenity>();
        }
    
        public int AmenityId { get; set; }
        public string AmenityName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual AmenityCategory AmenityCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomAmenity> RoomAmenity { get; set; }
    }
}
