//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingItem
    {
        public int ItemId { get; set; }
        public int BookingId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public System.DateTime ItemDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> DamageReportId { get; set; }
    
        public virtual DamageReport DamageReport { get; set; }
        public virtual Room Room { get; set; }
        public virtual Service Service { get; set; }
    }
}
