//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageEvidence
    {
        public int EvidenceId { get; set; }
        public int ReportId { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
    
        public virtual DamageReport DamageReport { get; set; }
    }
}
