//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DamageReport()
        {
            this.BookingItem = new HashSet<BookingItem>();
            this.DamageEvidence = new HashSet<DamageEvidence>();
            this.RoomMaintenance = new HashSet<RoomMaintenance>();
        }
    
        public int ReportId { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public int DamageTypeId { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int StatusId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingItem> BookingItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageEvidence> DamageEvidence { get; set; }
        public virtual DamageType DamageType { get; set; }
        public virtual Room Room { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomMaintenance> RoomMaintenance { get; set; }
    }
}
