//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelServiceEntities : DbContext
    {
        public HotelServiceEntities()
            : base("name=HotelServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenity> Amenity { get; set; }
        public virtual DbSet<AmenityCategory> AmenityCategory { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<BookingItem> BookingItem { get; set; }
        public virtual DbSet<BookingSource> BookingSource { get; set; }
        public virtual DbSet<BookingStatus> BookingStatus { get; set; }
        public virtual DbSet<DamageEvidence> DamageEvidence { get; set; }
        public virtual DbSet<DamageReport> DamageReport { get; set; }
        public virtual DbSet<DamageType> DamageType { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<FinancialStatus> FinancialStatus { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<GuestDocument> GuestDocument { get; set; }
        public virtual DbSet<GuestGroup> GuestGroup { get; set; }
        public virtual DbSet<LoyaltyTransaction> LoyaltyTransaction { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomAmenity> RoomAmenity { get; set; }
        public virtual DbSet<RoomImage> RoomImage { get; set; }
        public virtual DbSet<RoomMaintenance> RoomMaintenance { get; set; }
        public virtual DbSet<RoomStatus> RoomStatus { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskStatus> TaskStatus { get; set; }
        public virtual DbSet<TaskType> TaskType { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
