//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestDocument
    {
        public int DocumentId { get; set; }
        public int GuestId { get; set; }
        public int DocumentTypeId { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string DocumentSeries { get; set; }
        public string DocumentNumber { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public Nullable<int> UploadedBy { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual User User { get; set; }
    }
}
