//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyTransaction
    {
        public int TransactionId { get; set; }
        public int GuestId { get; set; }
        public int TypeId { get; set; }
        public int Points { get; set; }
        public Nullable<int> BookingId { get; set; }
        public string Description { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
