//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAmenity
    {
        public int RoomId { get; set; }
        public int AmenityId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Notes { get; set; }
    
        public virtual Amenity Amenity { get; set; }
        public virtual Room Room { get; set; }
    }
}
