//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomImage
    {
        public int RoomImageId { get; set; }
        public int RoomId { get; set; }
        public string ImagePath { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
