//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomMaintenance
    {
        public int MaintenanceId { get; set; }
        public int RoomId { get; set; }
        public int TaskTypeId { get; set; }
        public string IssueDescription { get; set; }
        public int Priority { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> DamageReportId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual DamageReport DamageReport { get; set; }
        public virtual Room Room { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual User User { get; set; }
    }
}
